# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [3]:
import numpy as np
import sys

## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [18]:
my_list = [0] * 1000
sys.getsizeof(my_list)

8056

In [22]:
numpy_array = np.zeros(1000, dtype=np.int8)
sys.getsizeof(numpy_array)

1112

## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [28]:
my_array = np.array([0.3, 1.7, 2.3, 3.9, 5.1, 5.5, 6.0, 7.5, 8.8, 9.2 ])
result = my_array[[0, 2, -1]]
print(result)

[0.3 2.3 9.2]


## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [15]:
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])
result = np.sum(array[[0, 1, 4, 7]])
print(result)

27.0


## Task 5

You have a matrix `A`:

```python
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])
```

Follow the comments in the next cells and write the code.

In [40]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [33]:
A.mean(axis=0)

array([2. , 8.4])

### Task 5.2 Get the standard deviation by `y` axis

In [35]:
A.std(axis=1)

array([2.5, 3. , 4. , 3.5, 3. ])

### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [52]:
np.sum(A, axis=1)

[ 7 10 14 13  8]


### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [53]:
A[:2]

array([[1, 6],
       [2, 8]])

##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [54]:
A[[0, 2, -1]]

array([[ 1,  6],
       [ 3, 11],
       [ 1,  7]])

## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [67]:
# Python code
import time

start_time = time.time()
python_list = [i for i in range(1000000)]
end_time = time.time()

execution_time_python = end_time - start_time
print("Execution time for Python code:", execution_time_python)

Execution time for Python code: 0.08792543411254883


In [64]:
start_time = time.time()
np.arange(1000000).tolist()
end_time = time.time()

execution_time_numpy = end_time - start_time
print("Execution time for NumPy code:", execution_time_numpy)

Execution time for NumPy code: 0.04690241813659668


### Task 6.2

In [73]:
# Python code
def unknown_signature(vector1, vector2):
    result = 0
    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]
    return result

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]
result_python = unknown_signature(vector1, vector2)

%time unknown_signature(vector1, vector2)
result_python

CPU times: total: 0 ns
Wall time: 0 ns


32

In [74]:
def unknown_signature(vector1, vector2):
    return np.dot(vector1, vector2)

result_numpy = unknown_signature(vector1, vector2)
%time unknown_signature(vector1, vector2)
result_numpy

CPU times: total: 0 ns
Wall time: 0 ns


32

### Task 6.3

In [81]:
# Python code
def unknown_signature(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

In [79]:
def unknown_signature(matrix1, matrix2):
    return np.multiply(matrix1, matrix2)

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]
%time unknown_signature(matrix1, matrix2)
unknown_signature(matrix1, matrix2)

CPU times: total: 0 ns
Wall time: 15.6 ms


array([[ 5, 12],
       [21, 32]])

### Task 6.4

In [ ]:
# Python code
def unknown_signature(lst):
    total = 0
    for num in lst:
        total += num
    result = total / len(lst)
    return result

lst = [1, 2, 3, 4, 5]

In [84]:
def unknown_signature(lst):
    return np.mean(lst)

lst = [1, 2, 3, 4, 5]
%time unknown_signature(lst)
unknown_signature(lst)

CPU times: total: 0 ns
Wall time: 15.6 ms


3.0

## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [ ]:
# Python code
def unknown_signature(lst, mask, new_value):
    for i in range(len(lst)):
        if mask[i]:
            lst[i] = new_value

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
unknown_signature(lst, mask, new_value)
lst

In [89]:
def unknown_signature(lst, mask, new_value):
    return np.where(mask, new_value, lst)

lst = np.array([1, 2, 3, 4, 5])
mask = np.array([True, False, True, False, True])
new_value = 0
%time unknown_signature(lst, mask, new_value)
result = unknown_signature(lst, mask, new_value)
result

CPU times: total: 0 ns
Wall time: 0 ns


array([0, 2, 0, 4, 0])

### Task 7.2

In [94]:
# Python code
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

In [105]:
def unknown_signature(lst1, lst2):
    return (~lst1).tolist(), (lst1 & lst2).tolist(), (lst1 | lst2).tolist()

list1 = np.array([5, 2, 7, 4, 9], dtype=np.int8)
list2 = np.array([3, 6, 1, 8, 10], dtype=np.int8)

%time unknown_signature(list1, list2)
unknown_signature(list1, list2)

CPU times: total: 0 ns
Wall time: 0 ns


([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

### Task 7.3 Optional

In [109]:
# Python code
def unknown_signature(lst):
    result = []
    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)
    return result

my_list = [6, 9, 12, 14, 17, 20]
result_python_style = unknown_signature(my_list)
result_python_style

[3, 13, 11, 21]

In [112]:
my_list = np.array([6, 9, 12, 14, 17, 20], dtype=np.int8) 

compare_mask = (my_list % 2 == 0) & ((my_list > 10) | (my_list % 3 == 0))
my_list = (my_list ^ 7) + 2

%time my_list[compare_mask].tolist()

CPU times: total: 0 ns
Wall time: 0 ns


[3, 13, 11, 21]